### ISSUE TITLE
Call to undefined method aharen\Language\Facades\Language::handle()

### ISSUE THREAD

**Issue by RasmusStougaard** [aharen/Language#2]
I get this after i installed it on a fresh laravel 5.4 install

**Comment by aharen** [comment]
Hi @RasmusStougaard,

i have not yet been able to test this on laravel 5.4 but have you added the Service Provider and Facade to config/app.php ??

Also, Can you please share a stack trace too

**Comment by RasmusStougaard** [comment]
ah yes i saw that as soon as i had posted.. But yeah it's all added. Guess
it has something to do with the version :)

2017-02-20 5:56 GMT+01:00 Ahmed Khusaam <notifications@github.com>:

**Comment by aharen** [comment]
I tested with laravel 5.4, minor hiccups found to which I have posted an update (updated the READ ME too)

Could you try now please
